== Guide for Object Detection with RHDE LAB

=== About this Guide


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SHORT INTRO TO THE LAB. IT MIGHT BE COPY/PASTED FROM THE DOCS INTRO 

BLAH, BLAH
!!!!!!!!!!!!!!!!!!!!!!!!!!





=== Accessing the Guide



==== GitHub Pages

You can take a view to the *static* content by simply visiting GitHub Pages for this repo in `https://luisarizmendi.github.io/guide-object-detection/modules/index.html`

==== Using Antora Viewer

You can access the content by using an antora-viewer container image:

. Clone the repo and `cd` into it
. When you make changes to the content, all you need is to kill the container and run it again.
+
[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

For SELinux environments, `:z` may need to be appended to the volume mount:

----
podman run --rm --name antora -v $PWD:/antora:z -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

Live-reload is not supported.

==== Using local file scripts

You can also

. Clone the repo and `cd` into it
. Run ./utilities/lab-serve
. Open http://localhost:8080 in your browser
. Run ./utilities/lab-build to build your html

To rebuild your html, run `./utilites/build`.



