 FROM registry.access.redhat.com/ubi9/python-39:latest AS base

 USER root
 
 RUN dnf install -y \
     python3 \
     python3-pip \
     gcc \
     unzip \
     git \
     python3-devel \
     podman \
     mesa-libGL \
     && dnf clean all \
     && python3 -m ensurepip --upgrade
     
 RUN python3 -m pip install --upgrade pip
 
 RUN python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

 RUN INSTALL_PKGS="ultralytics roboflow minio" && \
     pip install --no-cache-dir  $INSTALL_PKGS 

WORKDIR /opt/app-root/src

USER 1001

CMD ["/bin/bash"]
