= How to deploy the lab





== OpenShift

- create users in ocp




INSTALL:
gitops
minio storage  + create buckets
pipelines
flightctl








remove nvidia operator cluster object and recreate it



https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.16/html-single/working_with_accelerators/index#enabling-nvidia-gpus_accelerators










FROM fedora:latest

RUN dnf install -y \
    curl \
    && curl -O https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod +x mc \
    && mv mc /usr/local/bin/ \
    && dnf clean all

ENTRYPOINT ["mc"]

CMD ["--help"]










---
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-minio
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: bootstrap-lab
        image: quay.io/luisarizmendi/mc:latest 
        command: ["/bin/sh", "-c"]
        args:
        - |
            MINIO_ALIAS="minio"
            MINIO_URL="http://minio-service.larizmen-dev.svc.cluster.local:9000"
            ACCESS_KEY="admin"
            SECRET_KEY="R3dh4t1!"

            mkdir -p /tmp/mc-config
            export MC_CONFIG_DIR=/tmp/mc-config

            # Wait to be ready
            while true; do
                if mc alias set "$MINIO_ALIAS" "$MINIO_URL" "$ACCESS_KEY" "$SECRET_KEY"; then
                    echo "MinIO alias set successfully!"
                    break
                else
                    echo "Retrying in 2 seconds..."
                    sleep 2
                fi
            done

            for i in $(seq -w 1 25); do
                USER="user$i"
                PASSWORD="redhat$i"
                POLICY_FILE="/tmp/${USER}-policy.json"
                BUCKET_NAME="${USER}-ai"

                echo "Creating user: $USER with password: $PASSWORD"
                mc admin user add $MINIO_ALIAS $USER $PASSWORD

                echo "Creating policy for: $USER"
                cat > $POLICY_FILE << EOF
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "s3:ListBucket"
                        ],
                        "Resource": [
                            "arn:aws:s3:::${USER}-*"
                        ]
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "s3:PutObject",
                            "s3:DeleteObject",
                            "s3:GetObject"
                        ],
                        "Resource": [
                            "arn:aws:s3:::${USER}-*/*"
                        ]
                    }
                ]
            }
            EOF

                echo "Adding policy to MinIO: ${USER}-policy"
                mc admin policy create $MINIO_ALIAS ${USER}-policy $POLICY_FILE

                echo "Attaching policy to user: $USER"
                mc admin policy attach $MINIO_ALIAS ${USER}-policy --user=$USER

                echo "Creating bucket: $BUCKET_NAME"
                mc mb ${MINIO_ALIAS}/${BUCKET_NAME}

                # Clean up policy file
                rm -f $POLICY_FILE

                echo "User $USER setup complete."
                echo "-------------------------"
            done

            echo "Environment ready!"
      restartPolicy: Never
  backoffLimit: 1










mc alias set minio http://minio-service.larizmen-dev.svc.cluster.local:9000 admin R3dh4t1!








mc admin user add minio user01 redhat01

cat > user01-policy.json << EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::user01-*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::user01-*/*"
            ]
        }
    ]
}
EOF

mc admin policy create myminio user01-policy user01-policy.json

mc admin policy attach minio user01-policy --user=user01

mc mb minio/user01-ai

== Gitea
preparing the environment Gitea:
$ ansible-playbook playbook.yml -i inventory 

== FlighCTL

  # git clone repo
  # make sure you have the following packaes installed: git, make, and go (>= 1.21), openssl, openssl-devel, podman-compose
  # sudo dnf install git make golang openssl openssl-devel podman-compose
  # ensure podman socket is enabled : systemctl --user enable --now podman.socket
  # build repo: make build
  # install kind:
  #[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
  # install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux
  # install helm: https://helm.sh/docs/intro/install/#from-script
  # deploy using helm with kind local cluster (it includes installing helm)
  # make deploy
  # CANT USE LOCAL METHOD AS IT DOESN'T INCLUDE UI
  # install on cluster with acm
  # helm upgrade --install --version=0-latest     --namespace flightctl --create-namespace     flightctl oci://quay.io/flightctl/charts/flightctl     --values content/modules/ROOT/pages/scripts/environment/values.yaml
  # fix redis permission by patching ss with this user and group id: 1000860000
  # install flighctl cli https://github.com/flightctl/flightctl/blob/main/docs/user/getting-started.md#installing-the-flight-control-cli
  # login into flightctl
  # $ flightctl login https://api.flightctl.apps.my.lmf.openshift.es/  --insecure-skip-tls-verify --token=sha256~CGM1m_RbqBqS1bbNdakdGVRU6-2aRZlwzlexZLpVQ3Y
  # now you can get the devices registered with
  # flightctl get devices

== DNS - DHCP - Router Openwrt
using this guide https://openwrt.org/docs/guide-user/installation/openwrt_x86 I'll reuse a device at home
