= Day 2 Operations

== OS Configuration

With image-based Linux OSes, it is best practice to include OS-level / host configuration into the OS image for maximum consistency and repeatability. To update configuration, a new OS image should be created and devices updated to the new image.

However, there are scenarios where this is impractical, for example, when configuration is missing in the image, needs to be specific to a device, or needs to be update-able at runtime without updating the OS image and rebooting. For these cases, Flight Control allows users to declare a set of configuration files that shall be present on the device's file system.

Conceptually, this set of configuration files can be thought of as an additional, dynamic layer on top of the OS image's layers. The Flight Control Agent applies updates to this layer transactionally, ensuring that either all files have been successfully updated in the file system or have been returned to their pre-update state. Further, if the user updates both a devices OS and configuration set at the same time, the Flight Control Agent will first update the OS, then apply the specified configuration set on top.

    [!Important] After the Flight Control Agent has updated the configuration on disk, this configuration still needs to be activated. That means, running services need to reload the new configuration into memory for it to become effective. If the update involves a reboot, services will be restarted by systemd in the right order with the new configuration automatically. If the update does not involve a reboot, many services can detect changes to their configuration files and automatically reload them. When a service does not support this, you use Device Lifecycle Hooks to specify rules like "if configuration file X has changed, run command Y". Also refer to this section for the set of default rules that the Flight Control Agent applies.

Users can specify a list of configurations sets, in which case the Flight Control Agent applies the sets in sequence and on top of each other, such that in case of conflict the "last one wins".

Configuration can come from multiple sources, called "configuration providers" in Flight Control. Flight Control currently supports the following configuration providers:

    Git Config Provider: Fetches device configuration files from a Git repository.
    Kubernetes Secret Provider: Fetches a Secret from a Kubernetes cluster and writes its content to the device's file system.
    HTTP Config Provider: Fetches device configuration files from an HTTP(S) endpoint.
    Inline Config Provider: Allows specifying device configuration files inline in the device manifest without querying external systems.

using os configuration to deploy pull secret

== Application deployment

You can deploy, update, or undeploy applications on a device by updating the list of applications in the device's specification. The next time the agent checks in, it learns of the change in the specification, downloads any new or updated application packages and images from an OCI-compatible registry, and deploys them to the appropriate application runtime or removes them from that runtime.

The following table shows the application runtimes and formats supported by Flight Control:
Runtime 	Descriptor Format 	Package Format 	Package Repository 	Note
Podman 	podman-compose 	(name TBD) 	OCI registry 	requires podman-compose installed on device
Podman 	podman-compose 	(unpackaged) 	git or inline 	requires podman-compose installed on device
Podman 	Quadlet 	(name TBD) 	OCI registry 	
Podman 	Quadlet 	(unpackaged) 	git or inline 	
MicroShift 	Kubernetes manifests from Helm templates 	Helm Chart 	OCI registry 	requires helm installed on device
MicroShift 	Kubernetes manifests from kustomize 	(unpackaged) 	git or inline 	

To deploy an application to a device, create a new entry in the "applications" section of the device's specification, specifying the following parameters:
Parameter 	Description
Name 	A user-defined name for the application. This will be used when the web UI and CLI list applications.
Image 	A reference to an application package in an OCI registry.
EnvVars 	(Optional) A list of key/value-pairs that will be passed to the deployment tool as environment variables or command line flags.



using os configuration deploy manifest onto microshift

== OS Update

You can update a device's OS by updating the target OS image name or version in the device's specification. The next time the agent checks in, it learns of the requested update and automatically starts downloading and verifying the new OS version in the background. It then schedules the actual system update to be performed according to the update policy. When the time has come to update, it installs the new version in parallel and performs a reboot into the new version.

include cockpit-ostree to check device updates graphically

== Device Monitoring

You can set up monitors for device resources and define alerts when the utilization of these resources crosses a defined threshold. When the agent alerts the Flight Control service, the service sets the device status to "degraded" or "error" (depending on the severity level) and may suspend the rollout of updates and alarm the user as a result.

Note this is not meant to replace an observability solution. If your use case requires streaming logs and metrics from devices into an observability stack and the device's network bandwidth allows this, see Adding Device Observability for ways to approach that.

Resource monitors take the following parameters:
Parameter 	Description
MonitorType 	The resource to monitor. Currently supported resources are "CPU", "Memory", and "Disk". [TODO: Check whether the "Custom" resource type is implemented.]
SamplingInterval 	The interval in which the monitor samples utilization, specified as positive integer followed by a time unit ('s' for seconds, 'm' for minutes, 'h' for hours).
AlertRules 	A list of alert rules.
Path 	(Disk monitor only) The absolute path to the directory to monitor. Utilization reflects the filesystem containing the path, similar to df, even if it’s not a mount point.

Application monitoring with Flight Control

Move back to xref:index.adoc[Index]