apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-batch-model-api
  labels:
    app: object-detection-batch-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection-batch-model-api
  template:
    metadata:
      labels:
        app: object-detection-batch-model-api
    spec:
      containers:
      - name: batch-model-api
        image: quay.io/luisarizmendi/object-detection-batch-model-api:latest
        ports:
        - containerPort: 8800
---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-batch-model-api
  labels:
    app: object-detection-batch-model-api
spec:
  selector:
    app: object-detection-batch-model-api
  ports:
  - protocol: TCP
    port: 8800
    targetPort: 8800
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: object-detection-batch-model-api
  labels:
    app: object-detection-batch-model-api
spec:
  to:
    kind: Service
    name: object-detection-batch-model-api
  port:
    targetPort: 8800
